var sizesArr=dataSets.sizes,conArr=dataSets.connectivities,urlArr=dataSets.setURLs,dataCollectFinished=!1,graph=null,svgDocument,jDataReadyFirstTime=!0,viewWidth,viewHeight,myCamera,mouseX=0,mouseY=0,kb,timer,firstDrawTimer,serverTimer,numNodes,connectivity,times=[],timesIter,timesLoops;
function svgInit(){var a=sessionStorage.getItem("sizeIndex");a||(sessionStorage.setItem("sizeIndex",0),a=0);var b=sessionStorage.getItem("conIndex");b||(sessionStorage.setItem("conIndex",0),b=0);sessionStorage.getItem("urlIndex")||sessionStorage.setItem("urlIndex",0);(svgDocument=document.getElementById("svgEmbed").contentDocument)?(myCamera=new Camera(svgDocument,"SVG"),timesLoops=20,times[0]=0,times[1]=timesLoops,timesIter=times[102]=0,numNodes=sizesArr[a],connectivity=conArr[b],makeGraph()):setTimeout("svgInit();",
20)}
function makeGraph(){if(graph){var a=graph.nodesGroupSVG;if(a)a.parentNode.removeChild(a),graph.nodesGroupSVG=null;if(a=graph.edgesGroupSVG)a.parentNode.removeChild(a),graph.edgesGroupSVG=null;graph.destroy()}jDataReadyFirstTime=!0;timer=new StopWatch;firstDrawTimer=new StopWatch;serverTimer=new StopWatch;firstDrawTimer.expired=!1;graph=new Graph(svgDocument,"SVG");graph.readJSON([firstDrawTimer,serverTimer],numNodes,connectivity);svgDocument.drawToolTip=myDrawToolTip;svgDocument.eraseToolTip=myEraseToolTip;
svgDocument.highlightFX=myHighlightFX;svgDocument.setHoverBg=mySetHoverBg;updateSVG()}function myDrawToolTip(){}function myEraseToolTip(){}function myHighlightFX(){}function mySetHoverBg(){}
function updateSVG(){if(graph.jsonReady){if(jDataReadyFirstTime)graph.draw&&graph.draw(),viewWidth=graph.jsonData.globalCoordinateInformation.width,viewHeight=graph.jsonData.globalCoordinateInformation.height,jDataReadyFirstTime=!1,myCamera.viewWidth=viewWidth,myCamera.viewHeight=viewHeight,myCamera.zoomToFit();myCamera.updateMouse(mouseX,mouseY);var a=svgDocument.getElementById("timerTxt");a.firstChild.data="render Time: "+times[timesIter+1];a=svgDocument.getElementById("graphTxt");a.firstChild.data=
"# Nodes: "+graph.numNodes+", # Edges: "+graph.numEdges;timer.start();if(!firstDrawTimer.expired){firstDrawTimer.expired=!0;var a=firstDrawTimer.getTime(),b=serverTimer.getTime();times[timesIter+2]=a;times[0]+=a;times[timesIter+103]=b;times[102]+=b;timesIter++;if(timesIter<timesLoops)setTimeout("makeGraph()",20);else{displayDataWindow(numNodes,connectivity,times,"Initial Rendering","SVG");var a=sessionStorage.getItem("sizeIndex"),b=sessionStorage.getItem("conIndex"),c=sessionStorage.getItem("urlIndex");
b++;b>2&&(b=0,a++);a>=sizesArr.length&&(c++,a=0);sessionStorage.setItem("sizeIndex",a);sessionStorage.setItem("conIndex",b);sessionStorage.setItem("urlIndex",c);window.location.href=urlArr[c]}}}else setTimeout("updateSVG()",20)};function Camera(a,b){this.centerY=this.centerX=0;this.zoom=1;this.invertedY=0;this.painter=a;this.needsRedraw=!0;this.mouseY=this.mouseX=0;this.zoomToFit=cameraZoomToFit;b=="SVG"?(this.cameraGroup=a.getElementById("cameraGroup"),this.width=a.documentElement.getAttribute("width"),this.height=a.documentElement.getAttribute("height"),this.moveTo=cameraMoveToSVG,this.setInvertedY=cameraInvYSVG,this.zoomTo=cameraZoomSVG,this.updateCTM=__cameraUpdateCTMSVG,this.updateMouse=cameraUpdateMouse,this.worldToCanvas=
cameraWorldToCanvas,this.viewStr="translate("+this.width/2+","+this.height/2+") ",this.invYStr=this.scaleStr="scale(1) ",this.moveTo(0,0)):a instanceof CanvasRenderingContext2D?(this.width=a.canvas.width,this.height=a.canvas.height,this.moveTo=cameraMoveToCanvas,this.setInvertedY=cameraInvYCanvas,this.zoomTo=cameraZoomCanvas,this.updateCTM=__cameraUpdateCTMCanvas,this.updateMouse=cameraUpdateMouse,this.worldToCanvas=cameraWorldToCanvas,this.moveTo(0,0)):a instanceof Array?(this.width=a[0].canvas.width,
this.height=a[0].canvas.height,this.moveTo=cameraMoveToCanvas,this.setInvertedY=cameraInvYCanvas,this.zoomTo=cameraZoomCanvas,this.updateCTM=__cameraUpdateCTMCanvasArr,this.updateMouse=cameraUpdateMouse,this.worldToCanvas=cameraWorldToCanvas,this.moveTo(0,0)):b=="Protovis"?(this.cameraGroup=a.transform,this.width=640,this.height=480,this.moveTo=cameraMoveToPV,this.zoomTo=cameraZoomPV,this.updateCTM=__cameraUpdateCTMPV,this.updateMouse=cameraUpdateMouse,this.worldToCanvas=cameraWorldToCanvas):alert("Caution: This camera doesn't have a painter.")}
function __cameraUpdateCTMCanvas(){this.painter.setTransform(1,0,0,1,0,0);this.painter.translate(this.width/2,this.height/2);this.invertedY&&this.painter.scale(1,-1);this.painter.scale(this.zoom,this.zoom);this.painter.translate(0-this.centerX,0-this.centerY);this.needsRedraw=!0}
function __cameraUpdateCTMCanvasArr(){for(var a in this.painter)this.painter[a].setTransform(1,0,0,1,0,0),this.painter[a].translate(this.width/2,this.height/2),this.invertedY&&this.painter[a].scale(1,-1),this.painter[a].scale(this.zoom,this.zoom),this.painter[a].translate(0-this.centerX,0-this.centerY);this.needsRedraw=!0}function __cameraUpdateCTMSVG(){this.needsRedraw=!0;this.cameraGroup.setAttributeNS(null,"transform",this.viewStr+this.invYStr+this.scaleStr+this.translateStr)}
function __cameraUpdateCTMPV(){this.needsRedraw=!0;this.painter.transform(pv.Transform.identity.translate(this.width/2,this.height/2).scale(this.zoom).translate((this.viewWidth-this.width)/2,(this.viewHeight-this.height)/2).translate(0-this.centerX,0-this.centerY))}function cameraMoveToCanvas(a,b){this.centerX=a;this.centerY=b;this.updateCTM()}function cameraMoveToSVG(a,b){this.centerX=a;this.centerY=b;this.translateStr="translate("+(0-a)+","+(0-b)+") ";this.updateCTM()}
function cameraMoveToPV(a,b){this.centerX=a;this.centerY=b;this.updateCTM()}function cameraInvYCanvas(a){var b=0;a&&(b=1);if(this.invertedY!=b)this.invertedY=1-this.invertedY,this.updateCTM()}function cameraInvYSVG(a){this.invYStr=a?"matrix(1,0,0,-1,0,0)":"scale(1) ";this.updateCTM()}function cameraZoomCanvas(a){this.zoom=a;this.updateCTM()}function cameraZoomSVG(a){this.scaleStr="scale("+a+") ";this.zoom=a;this.updateCTM()}function cameraZoomPV(a){this.zoom=a;this.updateCTM()}
function cameraUpdateMouse(a,b){var c=a/this.width,d=b/this.height;this.left=this.centerX-this.width/this.zoom/2;this.right=this.centerX+this.width/this.zoom/2;this.top=this.centerY-this.height/this.zoom/2;this.bottom=this.centerY+this.height/this.zoom/2;this.mouseX=(1-c)*this.left+c*this.right;this.mouseY=(1-d)*this.top+d*this.bottom}function cameraWorldToCanvas(a,b){return[(a-this.left)/(this.right-this.left)*this.width,(b-this.top)/(this.bottom-this.top)*this.height]}
function cameraZoomToFit(){this.moveTo(this.viewWidth/2,this.viewHeight/2);this.zoomTo(this.width/this.height>=this.viewWidth/this.viewHeight?this.height/this.viewHeight:this.width/this.viewWidth)}
function Graph(a,b){this.nodes=[];this.highlighted=[];this.numEdges=this.numNodes=0;this.painter=a;this.typeStr=b;this.jsonReady=!1;this.jsonData=null;this.addNode=graphAddNode;this.addEdge=graphAddEdge;this.readJSON=graphReadJSON;this.unhighlightAll=graphUnhighlightAll;this.destroy=graphDestroy;a instanceof SVGDocument||b=="SVG"?(this.draw=graphDrawSVG,this.drawToolTip=graphToolTipSVG,this.eraseToolTip=graphEraseToolTipSVG,this.highlightFX=graphHighlightFXSVG,this.drawNode=drawNodeSVG,this.numDrawnEdges=
0):a instanceof HTMLDocument?(this.draw=graphDrawCanvas,this.drawToolTip=graphToolTipCanvas,this.highlightFX=graphHighlightFXCanvas,this.drawNode=drawNodeCanvas,this.drawNodeToIDMap=drawNodeToIDMap,this.drawEdges=drawEdgesCanvas,this.getMouseNode=graphGetMouseNode,this.nodePen=a.getElementById("nodeGroup").getContext("2d"),this.edgePen=a.getElementById("edgeGroup").getContext("2d"),this.drawnEdges=[],this.needsRedraw=!0):b=="Protovis"?(this.draw=graphDrawPV,this.highlightFX=graphHighlightFXPV,this.drawnEdges=
[],this.numDrawnEdges=0):(alert("Caution: This graph doesn't have an appropriate painter."),this.addNode=graphAddNode2,this.highlightFX=this.eraseToolTip=this.drawToolTip=this.draw=null)}function graphDestroy(){for(var a in this.nodes)this.nodes[a].destroy();this.edgePen=this.nodePen=this.idMap=this.jsonData=this.painter=this.highlighted=this.drawnEdges=this.nodes=this.pvJSONedges=null}
function graphReadJSON(a,b,c){var d=null,f=null;a instanceof Array?(d=a[0],f=a[1]):d=a;f&&f.start();var e="http://localhost:8888/?graphId=cached&nodeQuantity="+b+"&nodeConnectivity="+c+"&callback=?";this.jsonReady=!1;var g=this;jQuery.ajaxSetup({error:ajaxError});jQuery.getJSON(e,{},function(h){var j=h.nodes,k=h.edges;jQuery.each(j,function(a,b){if(b.id==0)b.id="0";g.addNode(b.coordinate[0],b.coordinate[1],b.id,b.label)});jQuery.each(k,function(a,b){if(b.id==0)b.id="0";if(b.srcNodeId==0)b.srcNodeId=
"0";if(b.dstNodeId==0)b.dstNodeId="0";g.addEdge(b.srcNodeId,b.dstNodeId)});g.jsonData=h;g.jsonReady=!0;d.start();f&&f.pause();c=b=a=e=k=j=f=d=g=h=null});this.needsRedraw=!0}function ajaxError(a,b,c){alert("xhr: "+JSON.stringify(a)+"\nerror: "+c+"\nstatus:"+a.status)}function graphAddNode(a,b,c,d){if(!this.nodes[c])a=new Node(a,b,c,d),this.nodes[c]=a,this.highlighted[c]=0,this.numNodes++,this.needsRedraw=!0}
function graphAddNode2(a,b){if(!this.nodes[a]){var c=new Node(0,0,a,b);this.nodes[a]=c;this.numNodes++}}function graphAddEdge(a,b){var c=this.nodes[a],d=this.nodes[b];if(c&&d)c.addEdge(d),this.numEdges++,this.needsRedraw=!0}
function graphDrawSVG(){this.nodesGroupSVG=this.painter.createElementNS("http://www.w3.org/2000/svg","g");this.painter.getElementById("nodeGroup").appendChild(this.nodesGroupSVG);this.edgesGroupSVG=this.painter.createElementNS("http://www.w3.org/2000/svg","g");this.painter.getElementById("edgeGroup").appendChild(this.edgesGroupSVG);for(var a in this.nodes)this.drawNode(this.nodes[a])}
function drawNodeSVG(a){var b=this.painter,c=b.createElementNS("http://www.w3.org/2000/svg","circle");this.nodesGroupSVG.appendChild(c);c.id=a.id;c.setAttribute("cx",a.x);c.setAttribute("cy",a.y);var d=a.id;c.onmouseover=function(){b.drawToolTip(d)};c.onmouseout=function(){b.eraseToolTip(d)};c.onclick=function(){b.highlightFX(d)};c.setAttributeNS(null,"r","20");c.setAttributeNS(null,"style","fill:#00AAFF;stroke:#000000;stroke-width:3;shape-rendering:optimizeSpeed;pointer-events:visibleFill");for(var f in a.edges)if(c=
a.edges[f],!a.drawnEdges[f]){var e=b.createElementNS("http://www.w3.org/2000/svg","line");this.edgesGroupSVG.appendChild(e);e.setAttributeNS(null,"x1",a.x);e.setAttributeNS(null,"y1",a.y);e.setAttributeNS(null,"x2",c.x);e.setAttributeNS(null,"y2",c.y);e.setAttributeNS(null,"style","stroke:#000000;stroke-width:3;shape-rendering:optimizeSpeed;pointer-events:visibleFill");a.edgeSprites[c.id]=e;c.edgeSprites[a.id]=e;e=null;a.drawnEdges[f]=!0;c.drawnEdges[a.id]=!0;this.numDrawnEdges++}c=a=null}
function graphDrawCanvas(a){var b=this.edgePen;this.nodePen.lineWidth=3;b.lineWidth=3;this.idMapRes=5;this.idMap=[];var c;for(c=0;c<this.nodePen.canvas.width/this.idMapRes+1;c++)this.idMap[c]=[];for(c in this.nodes){var d=this.nodes[c];this.drawNode(d,a)}b.strokeStyle="#000000";b.miterLimit=4;this.numDrawnEdges=1;for(c in this.nodes)d=this.nodes[c],this.drawEdges(d);this.drawnEdges=[];this.needsRedraw=!1}
function drawNodeCanvas(a,b){var c=this.nodePen;graph.highlighted[a.id]?mpCircle(c,a.x,a.y,20,"#AA5500","#CCCC00"):mpCircle(c,a.x,a.y,20,"#000000","#00AAFF");this.drawNodeToIDMap(a,b)}
function drawNodeToIDMap(a,b){if(a.x+20>=b.left&&a.x-20<=b.right&&a.y+20>=b.top&&a.y-20<=b.bottom){var c=b.worldToCanvas(a.x,a.y),d=c[0]/this.idMapRes,c=c[1]/this.idMapRes,f=b.zoom*20/this.idMapRes,e=Math.floor(Math.min(d+f,b.width/this.idMapRes)),g=Math.floor(Math.max(c-f,0)),h=Math.floor(Math.min(c+f,b.height/this.idMapRes)),j,k;for(j=Math.floor(Math.max(d-f,0));j<e;j++)for(k=g;k<h;k++)if((d-j)*(d-j)+(c-k)*(c-k)<=f*f)this.idMap[j][k]=a.id}}
function drawEdgesCanvas(a){var b=this.edgePen,c;for(c in a.edges){var d=a.edges[c];this.drawnEdges[c+","+a.id]||(b.beginPath(),b.moveTo(a.x,a.y),b.lineTo(d.x,d.y),b.stroke(),this.drawnEdges[c+","+a.id]=!0,this.drawnEdges[a.id+","+c]=!0)}}
function graphDrawPV(){this.pvJSONnodes=[];var a=this.pvJSONedges=[],b;for(b in this.nodes){var c=this.nodes[b];c.nodeName=c.label;c.group=0;c.highlighted=0;c.label=null;for(var d in c.edges)this.drawnEdges[d+","+b]||(a[this.numDrawnEdges]={source:b,target:d,value:1},this.drawnEdges[d+","+b]=!0,this.drawnEdges[b+","+d]=!0,this.numDrawnEdges++)}}
function graphToolTipSVG(a){var b=this.nodes[a],c=this.painter.createElementNS("http://www.w3.org/2000/svg","g");this.painter.getElementById("toolTips").appendChild(c);c.setAttributeNS(null,"id","tt"+a);var a=b.x-10,d=b.y+24,f=this.painter.createElementNS("http://www.w3.org/2000/svg","rect");c.appendChild(f);f.setAttribute("x",a);f.setAttribute("y",d);f.setAttribute("height",20);f.setAttributeNS(null,"style","fill:#FFFFAA;stroke:#AA5555;stroke-width:3");var e=svgDocument.createElementNS("http://www.w3.org/2000/svg",
"text"),b=svgDocument.createTextNode(b.label);e.appendChild(b);c.appendChild(e);e.setAttribute("x",a+5);e.setAttribute("y",d+17);e.setAttributeNS(null,"style","font-family:arial;font-size:8pt");f.setAttribute("width",e.getBBox().width+10)}
function graphToolTipCanvas(a,b){var c=this.nodePen,d=this.edgePen;c.lineWidth=3;d.lineWidth=3;if(d=this.getMouseNode(a,b)){var f=this.nodes[d],e=f.x-10,g=f.y+24;c.font="8pt arial";var h=c.measureText(f.label).width+10;mpRect(c,e,g,h,20,"#AA5555","#FFFFAA");c.lineWidth=1;mpText(c,f.label,e+5,g+5,"black","black");this.needsRedraw=!0}return d}function graphEraseToolTipSVG(a){(a=this.painter.getElementById("tt"+a))&&a.parentNode.removeChild(a)}
function graphHighlightFXSVG(a){var b=this.painter,c=this.nodes[a],d=[];d[a]=b.getElementById(a);for(i in c.edges)d[i]=b.getElementById(i);for(var f in d)this.highlighted[f]=1-this.highlighted[f],this.highlighted[f]?d[f].setAttributeNS(null,"style","fill:#CCCC00;stroke:#AA5500;stroke-width:3"):d[f].setAttributeNS(null,"style","fill:#00AAFF;stroke:#000000;stroke-width:3")}
function graphHighlightFXCanvas(a,b){var c=this.edgePen;this.nodePen.lineWidth=3;c.lineWidth=3;if(c=this.getMouseNode(a,b)){var d=this.nodes[c];this.highlighted[c]=1-this.highlighted[c];for(i in d.edges)this.highlighted[i]=1-this.highlighted[i];this.needsRedraw=!0}return c}function graphHighlightFXPV(a){a=this.nodes[a];a.highlighted=1-a.highlighted;for(i in a.edges){var b=a.edges[i];b.highlighted=1-b.highlighted}this.needsRedraw=!0}
function graphGetMouseNode(a,b){return this.idMap[Math.floor(a/this.idMapRes)]==null?null:this.idMap[Math.floor(a/this.idMapRes)][Math.floor(b/this.idMapRes)]}
function graphUnhighlightAll(){var a;if(this.typeStr=="SVG"){var b=this.painter,c=[];for(a in this.nodes)this.highlighted[a]&&(c[a]=b.getElementById(a),this.highlighted[a]=0);for(a in c)c[a].setAttributeNS(null,"style","fill:#00AAFF;stroke:#000000;stroke-width:3")}else if(this.typeStr=="Protovis"){b=this.nodes;for(a in b)b[a].highlighted=0;vis.render()}else for(a in this.nodes)this.highlighted[a]=0}
function Keyboard(){this.keyPressed=[];this.keyTyped=[];this.lastPressed=0;this.A=65;this.C=67;this.R=82;this.S=83;this.W=87;this.Q=81;this.MINUS=109;this.EQUALS=61;this.setKeyDown=keyboardSetKeyDown;this.setKeyUp=keyboardSetKeyUp;this.pressed=keyboardPressed;this.typed=keyboardTyped}function keyboardSetKeyDown(a){a=a.which?a.which:a.keyCode;this.keyPressed[a]=!0;this.lastPressed=a}function keyboardSetKeyUp(a){a=a.which?a.which:a.keyCode;this.keyPressed[a]=!1;this.keyTyped[a]=!1}
function keyboardPressed(a){return this.keyPressed[a]?!0:!1}function keyboardTyped(a){return this.keyPressed[a]&&!this.keyTyped[a]?this.keyTyped[a]=!0:!1}function Node(a,b,c,d){this.x=a;this.y=b;this.id=c;this.numEdges=0;this.edges=[];this.drawnEdges=[];this.edgeSprites=[];this.label=d?d:c;this.addEdge=nodeAddEdge;this.hasEdge=nodeHasEdge;this.destroy=nodeDestroy}function nodeDestroy(){this.edgeSprites=this.drawnEdges=this.edges=null}
function nodeAddEdge(a){this.edges[a.id]==null&&(this.edges[a.id]=a,a.addEdge(this),this.numEdges++)}function nodeHasEdge(a){return this.edges[a.id]?!0:!1}function StopWatch(){this.curDate=new Date;this.stoppedTime=this.lastDate=this.curDate.getTime();this.elapsedTime=0;this.isRunning=!1;this.start=stopwatchStart;this.getTime=stopwatchGetTime;this.pause=stopwatchPause;this.unpause=stopwatchUnpause}
function stopwatchStart(){this.curDate=new Date;this.lastDate=this.curDate.getTime();this.elapsedTime=0;this.isRunning=!0}function stopwatchGetTime(){this.isRunning?(this.curDate=new Date,this.elapsedTime=this.curDate.getTime()-this.lastDate):this.elapsedTime=this.stoppedTime-this.lastDate;return this.elapsedTime}function stopwatchPause(){this.curDate=new Date;this.isRunning=!1;this.stoppedTime=this.curDate.getTime()}
function stopwatchUnpause(){this.curDate=new Date;this.isRunning=!0;this.lastDate+=this.curDate.getTime()-this.stoppedTime}
function displayDataWindow(a,b,c,d,f){var e=window.open("","","width=640,height=480"),g="<html><head></head>";g+="<body style='font-size:10pt'>";g+="<b>Web-based Large Graph Visualization project</b><br/>";g+="Data collection form <br/><br/>";g+="Measuring: "+d+"<br/><br/>";g+="Tool: "+f+"<br/><br/>";g+="# Nodes: "+a+"<br/>";g+="Connectivity: "+b+"<br/><br/>";if(d=="Initial Rendering"){g+="Server Time (ms) <br/><br/>";g+="<table style='border-collapse:collapse; padding:5px; border:1px solid black;'>";
for(a=0;a<c[1];a++)a%10==0&&(g+="<tr>"),g+="<td style='width:70px; font-size:10pt; border:1px solid black;'> "+c[a+103]+" </td>",a%10==9&&(g+="</tr>");g+="</table><br/>";g+="Average time (ms): "+c[102]/c[1]+"<br /><br />"}g+="Draw Times (ms) <br/><br/>";g+="<table style='border-collapse:collapse; padding:5px; border:1px solid black;'>";for(a=0;a<c[1];a++)a%10==0&&(g+="<tr>"),g+="<td style='width:70px; font-size:10pt; border:1px solid black;'> "+c[a+2]+" </td>",a%10==9&&(g+="</tr>");g+="</table><br/>";
g+="Average time (ms): "+c[0]/c[1]+"<br /><br />";d=="Initial Rendering"&&(g+="<b>Total Average time (ms):</b> "+(c[0]/c[1]+c[102]/c[1])+"<br /><br />");g+="<form><input type='button' value='Print' onclick='window.print();' /></form>";g+="</body></html>";e.document.write(g);e.blur()}
function interactiveMacro(a,b,c,d,f){this.iter=0;this.evt=new fakeEvent;this.painterX=a;this.painterY=b;this.kb=c;this.graph=d;this.camera=f;this.go=macroGo;this.setMouse=macroMouse;this.moveMouse=macroMoveMouse;this.resetKB=macroResetKB;this.keyPress=macroKeyPress}function fakeEvent(){this.clientY=this.clientX=this.which=0}
function macroGo(){this.resetKB();console.log(this.iter);this.iter==0&&(this.keyPress(this.kb.R),this.setMouse(-20,-20),myOnmousedown(this.evt));this.iter==0&&(this.moveMouse(-100,-100),this.keyPress(this.kb.EQUALS));this.iter==1&&(this.moveMouse(100,100),this.keyPress(this.kb.MINUS));if(this.iter==2){myOnmouseup(this.evt);this.keyPress(this.kb.R);var a=this.graph.nodes[0],b=this.camera.worldToCanvas(a.x,a.y);this.setMouse(b[0],b[1]);myOnmousedown(this.evt);this.setMouse(320,200);clickedNode=a.id}this.iter>=
3&&this.iter<5&&(this.keyPress(this.kb.EQUALS),this.moveMouse(100,50));this.iter==5&&(this.keyPress(this.kb.EQUALS),this.moveMouse(-100,40));this.iter++;if(this.iter==6)this.iter=0,myOnmouseup(this.evt),this.resetKB()}function macroMouse(a,b){this.evt.clientX=a+this.painterX;this.evt.clientY=b+this.painterY;myOnmousemove(this.evt)}function macroMoveMouse(a,b){this.evt.clientX+=a;this.evt.clientY+=b;myOnmousemove(this.evt)}function macroResetKB(){this.kb.keyPressed=[];this.kb.keyTyped=[]}
function macroKeyPress(a){this.evt.which=a;this.kb.setKeyDown(this.evt)}var mpTransR=0,mpTransG=0,mpTransB=0,mpTransTol=0;function mpClear(a,b){var c=a.canvas.width,d=a.canvas.height;if(b){if(b instanceof mpLinearGradient||b instanceof mpRadialGradient)a.fillStyle=b.makeGrad(a,0,0,c,d);else if(b instanceof mpPattern)a.fillStyle=b.makePat(a,0,0);else if(b instanceof Camera){a.clearRect(b.left,b.top,c/b.zoom,d/b.zoom);return}else a.fillStyle=b;a.fillRect(0,0,c,d)}else a.clearRect(0,0,c,d)}
function mpCircle(a,b,c,d,f,e){if(f)a.strokeStyle=f instanceof mpLinearGradient||f instanceof mpRadialGradient?f.makeGrad(a,b-d,c-d,d*2,d*2):f instanceof mpPattern?f.makePat(a,b-d,c-d):f;if(e)a.fillStyle=e instanceof mpLinearGradient||e instanceof mpRadialGradient?e.makeGrad(a,b-d,c-d,d*2,d*2):e instanceof mpPattern?e.makePat(a,b-d,c-d):e;__mpCircleHelper(a,b,c,d,f,e)}function __mpCircleHelper(a,b,c,d,f,e){a.beginPath();a.arc(b,c,d,0,Math.PI*2,!0);e&&a.fill();a.stroke()}
function mpEllipse(a,b,c,d,f,e,g){a.beginPath();a.save();a.translate(b,c);a.scale(1,f/d);a.arc(0,0,d,0,Math.PI*2,!0);a.restore();if(e)a.strokeStyle=e instanceof mpLinearGradient||e instanceof mpRadialGradient?e.makeGrad(a,b-d,c-f,d*2,f*2):e instanceof mpPattern?e.makePat(a,b-d,c-f):e;if(g)a.fillStyle=g instanceof mpLinearGradient||g instanceof mpRadialGradient?g.makeGrad(a,b-d,c-f,d*2,f*2):g instanceof mpPattern?g.makePat(a,b-d,c-f):g,a.fill();a.stroke()}
function mpRect(a,b,c,d,f,e,g){if(e)a.strokeStyle=e instanceof mpLinearGradient||e instanceof mpRadialGradient?e.makeGrad(a,b,c,d,f):e instanceof mpPattern?e.makePat(a,b,c):e;if(g)a.fillStyle=g instanceof mpLinearGradient||g instanceof mpRadialGradient?g.makeGrad(a,b,c,d,f):g instanceof mpPattern?g.makePat(a,b,c):g,a.fillRect(b,c,d,f);a.strokeRect(b,c,d,f)}
function mpRoundedRect(a,b,c,d,f,e,g,h){var j=function(a){return a/180*Math.PI};a.beginPath();a.moveTo(b+e,c);a.lineTo(b+d-e,c);a.arc(b+d-e,c+e,e,j(270),j(0),!1);a.lineTo(b+d,c+f-e);a.arc(b+d-e,c+f-e,e,j(0),j(90),!1);a.lineTo(b+e,c+f);a.arc(b+e,c+f-e,e,j(90),j(180),!1);a.lineTo(b,c+e);a.arc(b+e,c+e,e,j(180),j(270),!1);if(g)a.strokeStyle=g instanceof mpLinearGradient||g instanceof mpRadialGradient?g.makeGrad(a,b,c,d,f):g instanceof mpPattern?g.makePat(a,b,c):g;if(h)a.fillStyle=h instanceof mpLinearGradient||
h instanceof mpRadialGradient?h.makeGrad(a,b,c,d,f):h instanceof mpPattern?h.makePat(a,b,c):h,a.fill();a.stroke()}function mpLine(a,b,c,d,f,e){if(e)a.strokeStyle=e instanceof mpLinearGradient||e instanceof mpRadialGradient?e.makeGrad(a,b,c,d-b,f-c):e instanceof mpPattern?e.makePat(a,x,y):e;__mpLineHelper(a,b,c,d,f,e)}function __mpLineHelper(a,b,c,d,f){a.beginPath();a.moveTo(b,c);a.lineTo(d,f);a.stroke()}
function mpText(a,b,c,d,f,e,g){var h=a.measureText(b);g?h.width=g:g=h.width;h.height=a.measureText("m").width;if(f)a.strokeStyle=f instanceof mpLinearGradient||f instanceof mpRadialGradient?f.makeGrad(a,c,d,h.width,h.height):f instanceof mpPattern?f.makePat(a,c,d):f;a.fillStyle=e?e instanceof mpLinearGradient||e instanceof mpRadialGradient?e.makeGrad(a,c,d,h.width,h.height):e instanceof mpPattern?e.makePat(a,c,d):e:a.strokeStyle;a.fillText(b,c,d+h.height,g);a.strokeText(b,c,d+h.height,g)}
function mpImage(a,b,c,d,f,e){e?mpTransTol>0?(b=__mpApplyTransparentColor(a,b,f,e,0,0,b.width,b.height),a.drawImage(b,c,d)):a.drawImage(b,c,d,f,e):(mpTransTol>0&&(b=__mpApplyTransparentColor(a,b,f,e,0,0,b.width,b.height)),a.drawImage(b,c,d))}function mpImageBlitter(a,b,c,d,f,e,g,h,j,k){mpTransTol>0?(b=__mpApplyTransparentColor(a,b,f,e,g,h,j,k),a.drawImage(b,c,d)):a.drawImage(b,g,h,j,k,c,d,f,e)}function mpSetTransColor(a,b,c,d){mpTransR=a;mpTransG=b;mpTransB=c;mpTransTol=d}
function __mpApplyTransparentColor(a,b,c,d,f,e,g,h){a=document.createElement("canvas");a.width=c;a.height=d;var j=a.getContext("2d");j.mozImageSmoothingEnabled=!1;j.drawImage(b,f,e,g,h,0,0,c,d);b=j.getImageData(0,0,c,d);c=b.data;for(d=d=0;d<c.length;d+=4)Math.abs(c[d]-mpTransR)<=mpTransTol&&Math.abs(c[d+1]-mpTransG)<=mpTransTol&&Math.abs(c[d+2]-mpTransB)<=mpTransTol&&(c[d+3]=0);j.putImageData(b,0,0);return a}
function mpLinearGradient(a,b,c,d){this.x1=a;this.y1=b;this.x2=c;this.y2=d;this.stopPos=[];this.stopColor=[];this.numStops=0;this.addColorStop=function(a,b){var c=this.numStops;this.stopPos[c]=a;this.stopColor[c]=b;this.numStops++};this.makeGrad=function(a,b,c,d,j){a=a.createLinearGradient(b+d*this.x1,c+j*this.y1,b+d*this.x2,c+j*this.y2);for(b=0;b<this.numStops;b++)a.addColorStop(this.stopPos[b],this.stopColor[b]);return a}}
function mpRadialGradient(a,b,c,d,f,e){this.x1=a;this.y1=b;this.r1=c;this.x2=d;this.y2=f;this.r2=e;this.stopPos=[];this.stopColor=[];this.numStops=0;this.addColorStop=function(a,b){var c=this.numStops;this.stopPos[c]=a;this.stopColor[c]=b;this.numStops++};this.makeGrad=function(a,b,c,d,e){a=a.createRadialGradient(b+d*this.x1,c+e*this.y1,Math.max(d,e)*this.r1,b+d*this.x2,c+e*this.y2,Math.max(d,e)*this.r2);for(b=0;b<this.numStops;b++)a.addColorStop(this.stopPos[b],this.stopColor[b]);return a}}
function mpPattern(a,b,c,d,f,e){this.img=a;this.type=b;this.xOff=c;this.yOff=d;this.w=f;this.h=e;this.makePat=function(a,b,c){a=Math.floor(b%this.w-this.w);c=Math.floor(c%this.h-this.w);b=document.createElement("canvas");b.width=this.w;b.height=this.h;b.getContext("2d").drawImage(this.img,this.xOff,this.yOff,this.w,this.h);var d=document.createElement("canvas");d.width=this.w;d.height=this.h;var e=d.getContext("2d"),f,l;for(f=0;f<2;f++)for(l=0;l<2;l++)e.drawImage(b,0,0,this.w,this.h,a+this.w*f,c+
this.h*l,this.w,this.h);return e.createPattern(d,this.type)}};
