var sizesArr=dataSets.sizes,conArr=dataSets.connectivities,urlArr=dataSets.setURLs,dataCollectFinished=!1,graph,jData,jDataReadyFirstTime=!0,viewWidth,viewHeight,pen,edgePen,bgPen,hidPen,myCamera,bgPtrn,mouseX=0,mouseY=0,mouseClicked=!1,kb,timer,firstDrawTimer,serverTimer,numNodes,connectivity,times=[],timesIter,timesLoops;
$(document).ready(function(){var a=sessionStorage.getItem("sizeIndex");a||(sessionStorage.setItem("sizeIndex",0),a=0);var c=sessionStorage.getItem("conIndex");c||(sessionStorage.setItem("conIndex",0),c=0);sessionStorage.getItem("urlIndex")||sessionStorage.setItem("urlIndex",0);var b=document.getElementById("edgeGroup");edgePen=b.getContext("2d");b=document.getElementById("nodeGroup");pen=b.getContext("2d");b=document.getElementById("bgCanvas");bgpen=b.getContext("2d");b=document.getElementById("canvasHidden");
hidpen=b.getContext("2d");var b=document.createElement("canvas"),d=b.getContext("2d");b.width=32;b.height=32;mpRect(d,0,0,16,16,"lightblue","lightblue");mpRect(d,16,16,16,16,"lightblue","lightblue");bgPtrn=new mpPattern(b,"repeat",0,0,32,32);myCamera=new Camera([edgePen,pen]);myCamera.moveTo(320,240);timesLoops=20;times[0]=0;times[1]=timesLoops;timesIter=times[102]=0;numNodes=sizesArr[a];connectivity=conArr[c];makeGraph()});
function makeGraph(){jDataReadyFirstTime=!0;timer=new StopWatch;firstDrawTimer=new StopWatch;serverTimer=new StopWatch;firstDrawTimer.expired=!1;graph&&graph.destroy();graph=new Graph(document);graph.readJSON([firstDrawTimer,serverTimer],numNodes,connectivity);updateCanvas()}
function updateCanvas(){if(graph.jsonReady){if(jDataReadyFirstTime)viewWidth=graph.jsonData.globalCoordinateInformation.width,viewHeight=graph.jsonData.globalCoordinateInformation.height,jDataReadyFirstTime=!1,myCamera.viewWidth=viewWidth,myCamera.viewHeight=viewHeight,myCamera.zoomToFit();mpClear(bgpen,"white");mpClear(bgpen,bgPtrn);myCamera.updateMouse(mouseX,mouseY);mpClear(pen,myCamera);mpClear(edgePen,myCamera);pen.lineWidth=3;mpCircle(pen,0,0,10,"#9999CC","#9999CC");mpRect(pen,0,0,viewWidth,
viewHeight);graph.draw&&graph.draw(myCamera);mpText(bgpen,"render time: "+times[timesIter+1],10,50,"black","black");timesIter!=0&&mpText(bgpen,"# Nodes: "+graph.numNodes+", # Edges: "+graph.numEdges,10,70,"black","black");mpImage(bgpen,hidpen.canvas,0,0);timer.start();if(!firstDrawTimer.expired){firstDrawTimer.expired=!0;var a=firstDrawTimer.getTime(),c=serverTimer.getTime();times[timesIter+2]=a;times[0]+=a;times[timesIter+103]=c;times[102]+=c;timesIter++;if(timesIter<timesLoops)setTimeout("makeGraph()",
20);else{displayDataWindow(numNodes,connectivity,times,"Initial Rendering","Canvas");var a=sessionStorage.getItem("sizeIndex"),c=sessionStorage.getItem("conIndex"),b=sessionStorage.getItem("urlIndex");c++;c>2&&(c=0,a++);a>=sizesArr.length&&(b++,a=0);sessionStorage.setItem("sizeIndex",a);sessionStorage.setItem("conIndex",c);sessionStorage.setItem("urlIndex",b);window.location.href=urlArr[b]}}}else setTimeout("updateCanvas()",20)};function Camera(a,c){this.centerY=this.centerX=0;this.zoom=1;this.invertedY=0;this.painter=a;this.needsRedraw=!0;this.mouseY=this.mouseX=0;this.zoomToFit=cameraZoomToFit;c=="SVG"?(this.cameraGroup=a.getElementById("cameraGroup"),this.width=a.documentElement.getAttribute("width"),this.height=a.documentElement.getAttribute("height"),this.moveTo=cameraMoveToSVG,this.setInvertedY=cameraInvYSVG,this.zoomTo=cameraZoomSVG,this.updateCTM=__cameraUpdateCTMSVG,this.updateMouse=cameraUpdateMouse,this.worldToCanvas=
cameraWorldToCanvas,this.viewStr="translate("+this.width/2+","+this.height/2+") ",this.invYStr=this.scaleStr="scale(1) ",this.moveTo(0,0)):a instanceof CanvasRenderingContext2D?(this.width=a.canvas.width,this.height=a.canvas.height,this.moveTo=cameraMoveToCanvas,this.setInvertedY=cameraInvYCanvas,this.zoomTo=cameraZoomCanvas,this.updateCTM=__cameraUpdateCTMCanvas,this.updateMouse=cameraUpdateMouse,this.worldToCanvas=cameraWorldToCanvas,this.moveTo(0,0)):a instanceof Array?(this.width=a[0].canvas.width,
this.height=a[0].canvas.height,this.moveTo=cameraMoveToCanvas,this.setInvertedY=cameraInvYCanvas,this.zoomTo=cameraZoomCanvas,this.updateCTM=__cameraUpdateCTMCanvasArr,this.updateMouse=cameraUpdateMouse,this.worldToCanvas=cameraWorldToCanvas,this.moveTo(0,0)):c=="Protovis"?(this.cameraGroup=a.transform,this.width=640,this.height=480,this.moveTo=cameraMoveToPV,this.zoomTo=cameraZoomPV,this.updateCTM=__cameraUpdateCTMPV,this.updateMouse=cameraUpdateMouse,this.worldToCanvas=cameraWorldToCanvas):alert("Caution: This camera doesn't have a painter.")}
function __cameraUpdateCTMCanvas(){this.painter.setTransform(1,0,0,1,0,0);this.painter.translate(this.width/2,this.height/2);this.invertedY&&this.painter.scale(1,-1);this.painter.scale(this.zoom,this.zoom);this.painter.translate(0-this.centerX,0-this.centerY);this.needsRedraw=!0}
function __cameraUpdateCTMCanvasArr(){for(var a in this.painter)this.painter[a].setTransform(1,0,0,1,0,0),this.painter[a].translate(this.width/2,this.height/2),this.invertedY&&this.painter[a].scale(1,-1),this.painter[a].scale(this.zoom,this.zoom),this.painter[a].translate(0-this.centerX,0-this.centerY);this.needsRedraw=!0}function __cameraUpdateCTMSVG(){this.needsRedraw=!0;this.cameraGroup.setAttributeNS(null,"transform",this.viewStr+this.invYStr+this.scaleStr+this.translateStr)}
function __cameraUpdateCTMPV(){this.needsRedraw=!0;this.painter.transform(pv.Transform.identity.translate(this.width/2,this.height/2).scale(this.zoom).translate((this.viewWidth-this.width)/2,(this.viewHeight-this.height)/2).translate(0-this.centerX,0-this.centerY))}function cameraMoveToCanvas(a,c){this.centerX=a;this.centerY=c;this.updateCTM()}function cameraMoveToSVG(a,c){this.centerX=a;this.centerY=c;this.translateStr="translate("+(0-a)+","+(0-c)+") ";this.updateCTM()}
function cameraMoveToPV(a,c){this.centerX=a;this.centerY=c;this.updateCTM()}function cameraInvYCanvas(a){var c=0;a&&(c=1);if(this.invertedY!=c)this.invertedY=1-this.invertedY,this.updateCTM()}function cameraInvYSVG(a){this.invYStr=a?"matrix(1,0,0,-1,0,0)":"scale(1) ";this.updateCTM()}function cameraZoomCanvas(a){this.zoom=a;this.updateCTM()}function cameraZoomSVG(a){this.scaleStr="scale("+a+") ";this.zoom=a;this.updateCTM()}function cameraZoomPV(a){this.zoom=a;this.updateCTM()}
function cameraUpdateMouse(a,c){var b=a/this.width,d=c/this.height;this.left=this.centerX-this.width/this.zoom/2;this.right=this.centerX+this.width/this.zoom/2;this.top=this.centerY-this.height/this.zoom/2;this.bottom=this.centerY+this.height/this.zoom/2;this.mouseX=(1-b)*this.left+b*this.right;this.mouseY=(1-d)*this.top+d*this.bottom}function cameraWorldToCanvas(a,c){return[(a-this.left)/(this.right-this.left)*this.width,(c-this.top)/(this.bottom-this.top)*this.height]}
function cameraZoomToFit(){this.moveTo(this.viewWidth/2,this.viewHeight/2);this.zoomTo(this.width/this.height>=this.viewWidth/this.viewHeight?this.height/this.viewHeight:this.width/this.viewWidth)}
function Graph(a,c){this.nodes=[];this.highlighted=[];this.numEdges=this.numNodes=0;this.painter=a;this.typeStr=c;this.jsonReady=!1;this.jsonData=null;this.addNode=graphAddNode;this.addEdge=graphAddEdge;this.readJSON=graphReadJSON;this.unhighlightAll=graphUnhighlightAll;this.destroy=graphDestroy;a instanceof SVGDocument||c=="SVG"?(this.draw=graphDrawSVG,this.drawToolTip=graphToolTipSVG,this.eraseToolTip=graphEraseToolTipSVG,this.highlightFX=graphHighlightFXSVG,this.drawNode=drawNodeSVG,this.numDrawnEdges=
0):a instanceof HTMLDocument?(this.draw=graphDrawCanvas,this.drawToolTip=graphToolTipCanvas,this.highlightFX=graphHighlightFXCanvas,this.drawNode=drawNodeCanvas,this.drawNodeToIDMap=drawNodeToIDMap,this.drawEdges=drawEdgesCanvas,this.getMouseNode=graphGetMouseNode,this.nodePen=a.getElementById("nodeGroup").getContext("2d"),this.edgePen=a.getElementById("edgeGroup").getContext("2d"),this.drawnEdges=[],this.needsRedraw=!0):c=="Protovis"?(this.draw=graphDrawPV,this.highlightFX=graphHighlightFXPV,this.drawnEdges=
[],this.numDrawnEdges=0):(alert("Caution: This graph doesn't have an appropriate painter."),this.addNode=graphAddNode2,this.highlightFX=this.eraseToolTip=this.drawToolTip=this.draw=null)}function graphDestroy(){for(var a in this.nodes)this.nodes[a].destroy();this.edgePen=this.nodePen=this.idMap=this.jsonData=this.painter=this.highlighted=this.drawnEdges=this.nodes=this.pvJSONedges=null}
function graphReadJSON(a,c,b){var d=null,f=null;a instanceof Array?(d=a[0],f=a[1]):d=a;f&&f.start();var e="http://localhost:8888/?graphId=cached&nodeQuantity="+c+"&nodeConnectivity="+b+"&callback=?";this.jsonReady=!1;var g=this;jQuery.ajaxSetup({error:ajaxError});jQuery.getJSON(e,{},function(h){var j=h.nodes,k=h.edges;jQuery.each(j,function(a,b){if(b.id==0)b.id="0";g.addNode(b.coordinate[0],b.coordinate[1],b.id,b.label)});jQuery.each(k,function(a,b){if(b.id==0)b.id="0";if(b.srcNodeId==0)b.srcNodeId=
"0";if(b.dstNodeId==0)b.dstNodeId="0";g.addEdge(b.srcNodeId,b.dstNodeId)});g.jsonData=h;g.jsonReady=!0;d.start();f&&f.pause();b=c=a=e=k=j=f=d=g=h=null});this.needsRedraw=!0}function ajaxError(a,c,b){alert("xhr: "+JSON.stringify(a)+"\nerror: "+b+"\nstatus:"+a.status)}function graphAddNode(a,c,b,d){if(!this.nodes[b])a=new Node(a,c,b,d),this.nodes[b]=a,this.highlighted[b]=0,this.numNodes++,this.needsRedraw=!0}
function graphAddNode2(a,c){if(!this.nodes[a]){var b=new Node(0,0,a,c);this.nodes[a]=b;this.numNodes++}}function graphAddEdge(a,c){var b=this.nodes[a],d=this.nodes[c];if(b&&d)b.addEdge(d),this.numEdges++,this.needsRedraw=!0}
function graphDrawSVG(){this.nodesGroupSVG=this.painter.createElementNS("http://www.w3.org/2000/svg","g");this.painter.getElementById("nodeGroup").appendChild(this.nodesGroupSVG);this.edgesGroupSVG=this.painter.createElementNS("http://www.w3.org/2000/svg","g");this.painter.getElementById("edgeGroup").appendChild(this.edgesGroupSVG);for(var a in this.nodes)this.drawNode(this.nodes[a])}
function drawNodeSVG(a){var c=this.painter,b=c.createElementNS("http://www.w3.org/2000/svg","circle");this.nodesGroupSVG.appendChild(b);b.id=a.id;b.setAttribute("cx",a.x);b.setAttribute("cy",a.y);var d=a.id;b.onmouseover=function(){c.drawToolTip(d)};b.onmouseout=function(){c.eraseToolTip(d)};b.onclick=function(){c.highlightFX(d)};b.setAttributeNS(null,"r","20");b.setAttributeNS(null,"style","fill:#00AAFF;stroke:#000000;stroke-width:3;shape-rendering:optimizeSpeed;pointer-events:visibleFill");for(var f in a.edges)if(b=
a.edges[f],!a.drawnEdges[f]){var e=c.createElementNS("http://www.w3.org/2000/svg","line");this.edgesGroupSVG.appendChild(e);e.setAttributeNS(null,"x1",a.x);e.setAttributeNS(null,"y1",a.y);e.setAttributeNS(null,"x2",b.x);e.setAttributeNS(null,"y2",b.y);e.setAttributeNS(null,"style","stroke:#000000;stroke-width:3;shape-rendering:optimizeSpeed;pointer-events:visibleFill");a.edgeSprites[b.id]=e;b.edgeSprites[a.id]=e;e=null;a.drawnEdges[f]=!0;b.drawnEdges[a.id]=!0;this.numDrawnEdges++}b=a=null}
function graphDrawCanvas(a){var c=this.edgePen;this.nodePen.lineWidth=3;c.lineWidth=3;this.idMapRes=5;this.idMap=[];var b;for(b=0;b<this.nodePen.canvas.width/this.idMapRes+1;b++)this.idMap[b]=[];for(b in this.nodes){var d=this.nodes[b];this.drawNode(d,a)}c.strokeStyle="#000000";c.miterLimit=4;this.numDrawnEdges=1;for(b in this.nodes)d=this.nodes[b],this.drawEdges(d);this.drawnEdges=[];this.needsRedraw=!1}
function drawNodeCanvas(a,c){var b=this.nodePen;graph.highlighted[a.id]?mpCircle(b,a.x,a.y,20,"#AA5500","#CCCC00"):mpCircle(b,a.x,a.y,20,"#000000","#00AAFF");this.drawNodeToIDMap(a,c)}
function drawNodeToIDMap(a,c){if(a.x+20>=c.left&&a.x-20<=c.right&&a.y+20>=c.top&&a.y-20<=c.bottom){var b=c.worldToCanvas(a.x,a.y),d=b[0]/this.idMapRes,b=b[1]/this.idMapRes,f=c.zoom*20/this.idMapRes,e=Math.floor(Math.min(d+f,c.width/this.idMapRes)),g=Math.floor(Math.max(b-f,0)),h=Math.floor(Math.min(b+f,c.height/this.idMapRes)),j,k;for(j=Math.floor(Math.max(d-f,0));j<e;j++)for(k=g;k<h;k++)if((d-j)*(d-j)+(b-k)*(b-k)<=f*f)this.idMap[j][k]=a.id}}
function drawEdgesCanvas(a){var c=this.edgePen,b;for(b in a.edges){var d=a.edges[b];this.drawnEdges[b+","+a.id]||(c.beginPath(),c.moveTo(a.x,a.y),c.lineTo(d.x,d.y),c.stroke(),this.drawnEdges[b+","+a.id]=!0,this.drawnEdges[a.id+","+b]=!0)}}
function graphDrawPV(){this.pvJSONnodes=[];var a=this.pvJSONedges=[],c;for(c in this.nodes){var b=this.nodes[c];b.nodeName=b.label;b.group=0;b.highlighted=0;b.label=null;for(var d in b.edges)this.drawnEdges[d+","+c]||(a[this.numDrawnEdges]={source:c,target:d,value:1},this.drawnEdges[d+","+c]=!0,this.drawnEdges[c+","+d]=!0,this.numDrawnEdges++)}}
function graphToolTipSVG(a){var c=this.nodes[a],b=this.painter.createElementNS("http://www.w3.org/2000/svg","g");this.painter.getElementById("toolTips").appendChild(b);b.setAttributeNS(null,"id","tt"+a);var a=c.x-10,d=c.y+24,f=this.painter.createElementNS("http://www.w3.org/2000/svg","rect");b.appendChild(f);f.setAttribute("x",a);f.setAttribute("y",d);f.setAttribute("height",20);f.setAttributeNS(null,"style","fill:#FFFFAA;stroke:#AA5555;stroke-width:3");var e=svgDocument.createElementNS("http://www.w3.org/2000/svg",
"text"),c=svgDocument.createTextNode(c.label);e.appendChild(c);b.appendChild(e);e.setAttribute("x",a+5);e.setAttribute("y",d+17);e.setAttributeNS(null,"style","font-family:arial;font-size:8pt");f.setAttribute("width",e.getBBox().width+10)}
function graphToolTipCanvas(a,c){var b=this.nodePen,d=this.edgePen;b.lineWidth=3;d.lineWidth=3;if(d=this.getMouseNode(a,c)){var f=this.nodes[d],e=f.x-10,g=f.y+24;b.font="8pt arial";var h=b.measureText(f.label).width+10;mpRect(b,e,g,h,20,"#AA5555","#FFFFAA");b.lineWidth=1;mpText(b,f.label,e+5,g+5,"black","black");this.needsRedraw=!0}return d}function graphEraseToolTipSVG(a){(a=this.painter.getElementById("tt"+a))&&a.parentNode.removeChild(a)}
function graphHighlightFXSVG(a){var c=this.painter,b=this.nodes[a],d=[];d[a]=c.getElementById(a);for(i in b.edges)d[i]=c.getElementById(i);for(var f in d)this.highlighted[f]=1-this.highlighted[f],this.highlighted[f]?d[f].setAttributeNS(null,"style","fill:#CCCC00;stroke:#AA5500;stroke-width:3"):d[f].setAttributeNS(null,"style","fill:#00AAFF;stroke:#000000;stroke-width:3")}
function graphHighlightFXCanvas(a,c){var b=this.edgePen;this.nodePen.lineWidth=3;b.lineWidth=3;if(b=this.getMouseNode(a,c)){var d=this.nodes[b];this.highlighted[b]=1-this.highlighted[b];for(i in d.edges)this.highlighted[i]=1-this.highlighted[i];this.needsRedraw=!0}return b}function graphHighlightFXPV(a){a=this.nodes[a];a.highlighted=1-a.highlighted;for(i in a.edges){var c=a.edges[i];c.highlighted=1-c.highlighted}this.needsRedraw=!0}
function graphGetMouseNode(a,c){return this.idMap[Math.floor(a/this.idMapRes)]==null?null:this.idMap[Math.floor(a/this.idMapRes)][Math.floor(c/this.idMapRes)]}
function graphUnhighlightAll(){var a;if(this.typeStr=="SVG"){var c=this.painter,b=[];for(a in this.nodes)this.highlighted[a]&&(b[a]=c.getElementById(a),this.highlighted[a]=0);for(a in b)b[a].setAttributeNS(null,"style","fill:#00AAFF;stroke:#000000;stroke-width:3")}else if(this.typeStr=="Protovis"){c=this.nodes;for(a in c)c[a].highlighted=0;vis.render()}else for(a in this.nodes)this.highlighted[a]=0}
function Keyboard(){this.keyPressed=[];this.keyTyped=[];this.lastPressed=0;this.A=65;this.C=67;this.R=82;this.S=83;this.W=87;this.Q=81;this.MINUS=109;this.EQUALS=61;this.setKeyDown=keyboardSetKeyDown;this.setKeyUp=keyboardSetKeyUp;this.pressed=keyboardPressed;this.typed=keyboardTyped}function keyboardSetKeyDown(a){a=a.which?a.which:a.keyCode;this.keyPressed[a]=!0;this.lastPressed=a}function keyboardSetKeyUp(a){a=a.which?a.which:a.keyCode;this.keyPressed[a]=!1;this.keyTyped[a]=!1}
function keyboardPressed(a){return this.keyPressed[a]?!0:!1}function keyboardTyped(a){return this.keyPressed[a]&&!this.keyTyped[a]?this.keyTyped[a]=!0:!1}function Node(a,c,b,d){this.x=a;this.y=c;this.id=b;this.numEdges=0;this.edges=[];this.drawnEdges=[];this.edgeSprites=[];this.label=d?d:b;this.addEdge=nodeAddEdge;this.hasEdge=nodeHasEdge;this.destroy=nodeDestroy}function nodeDestroy(){this.edgeSprites=this.drawnEdges=this.edges=null}
function nodeAddEdge(a){this.edges[a.id]==null&&(this.edges[a.id]=a,a.addEdge(this),this.numEdges++)}function nodeHasEdge(a){return this.edges[a.id]?!0:!1}function StopWatch(){this.curDate=new Date;this.stoppedTime=this.lastDate=this.curDate.getTime();this.elapsedTime=0;this.isRunning=!1;this.start=stopwatchStart;this.getTime=stopwatchGetTime;this.pause=stopwatchPause;this.unpause=stopwatchUnpause}
function stopwatchStart(){this.curDate=new Date;this.lastDate=this.curDate.getTime();this.elapsedTime=0;this.isRunning=!0}function stopwatchGetTime(){this.isRunning?(this.curDate=new Date,this.elapsedTime=this.curDate.getTime()-this.lastDate):this.elapsedTime=this.stoppedTime-this.lastDate;return this.elapsedTime}function stopwatchPause(){this.curDate=new Date;this.isRunning=!1;this.stoppedTime=this.curDate.getTime()}
function stopwatchUnpause(){this.curDate=new Date;this.isRunning=!0;this.lastDate+=this.curDate.getTime()-this.stoppedTime}
function displayDataWindow(a,c,b,d,f){var e=window.open("","","width=640,height=480"),g="<html><head></head>";g+="<body style='font-size:10pt'>";g+="<b>Web-based Large Graph Visualization project</b><br/>";g+="Data collection form <br/><br/>";g+="Measuring: "+d+"<br/><br/>";g+="Tool: "+f+"<br/><br/>";g+="# Nodes: "+a+"<br/>";g+="Connectivity: "+c+"<br/><br/>";if(d=="Initial Rendering"){g+="Server Time (ms) <br/><br/>";g+="<table style='border-collapse:collapse; padding:5px; border:1px solid black;'>";
for(a=0;a<b[1];a++)a%10==0&&(g+="<tr>"),g+="<td style='width:70px; font-size:10pt; border:1px solid black;'> "+b[a+103]+" </td>",a%10==9&&(g+="</tr>");g+="</table><br/>";g+="Average time (ms): "+b[102]/b[1]+"<br /><br />"}g+="Draw Times (ms) <br/><br/>";g+="<table style='border-collapse:collapse; padding:5px; border:1px solid black;'>";for(a=0;a<b[1];a++)a%10==0&&(g+="<tr>"),g+="<td style='width:70px; font-size:10pt; border:1px solid black;'> "+b[a+2]+" </td>",a%10==9&&(g+="</tr>");g+="</table><br/>";
g+="Average time (ms): "+b[0]/b[1]+"<br /><br />";d=="Initial Rendering"&&(g+="<b>Total Average time (ms):</b> "+(b[0]/b[1]+b[102]/b[1])+"<br /><br />");g+="<form><input type='button' value='Print' onclick='window.print();' /></form>";g+="</body></html>";e.document.write(g);e.blur()}
function interactiveMacro(a,c,b,d,f){this.iter=0;this.evt=new fakeEvent;this.painterX=a;this.painterY=c;this.kb=b;this.graph=d;this.camera=f;this.go=macroGo;this.setMouse=macroMouse;this.moveMouse=macroMoveMouse;this.resetKB=macroResetKB;this.keyPress=macroKeyPress}function fakeEvent(){this.clientY=this.clientX=this.which=0}
function macroGo(){this.resetKB();console.log(this.iter);this.iter==0&&(this.keyPress(this.kb.R),this.setMouse(-20,-20),myOnmousedown(this.evt));this.iter==0&&(this.moveMouse(-100,-100),this.keyPress(this.kb.EQUALS));this.iter==1&&(this.moveMouse(100,100),this.keyPress(this.kb.MINUS));if(this.iter==2){myOnmouseup(this.evt);this.keyPress(this.kb.R);var a=this.graph.nodes[0],c=this.camera.worldToCanvas(a.x,a.y);this.setMouse(c[0],c[1]);myOnmousedown(this.evt);this.setMouse(320,200);clickedNode=a.id}this.iter>=
3&&this.iter<5&&(this.keyPress(this.kb.EQUALS),this.moveMouse(100,50));this.iter==5&&(this.keyPress(this.kb.EQUALS),this.moveMouse(-100,40));this.iter++;if(this.iter==6)this.iter=0,myOnmouseup(this.evt),this.resetKB()}function macroMouse(a,c){this.evt.clientX=a+this.painterX;this.evt.clientY=c+this.painterY;myOnmousemove(this.evt)}function macroMoveMouse(a,c){this.evt.clientX+=a;this.evt.clientY+=c;myOnmousemove(this.evt)}function macroResetKB(){this.kb.keyPressed=[];this.kb.keyTyped=[]}
function macroKeyPress(a){this.evt.which=a;this.kb.setKeyDown(this.evt)}var mpTransR=0,mpTransG=0,mpTransB=0,mpTransTol=0;function mpClear(a,c){var b=a.canvas.width,d=a.canvas.height;if(c){if(c instanceof mpLinearGradient||c instanceof mpRadialGradient)a.fillStyle=c.makeGrad(a,0,0,b,d);else if(c instanceof mpPattern)a.fillStyle=c.makePat(a,0,0);else if(c instanceof Camera){a.clearRect(c.left,c.top,b/c.zoom,d/c.zoom);return}else a.fillStyle=c;a.fillRect(0,0,b,d)}else a.clearRect(0,0,b,d)}
function mpCircle(a,c,b,d,f,e){if(f)a.strokeStyle=f instanceof mpLinearGradient||f instanceof mpRadialGradient?f.makeGrad(a,c-d,b-d,d*2,d*2):f instanceof mpPattern?f.makePat(a,c-d,b-d):f;if(e)a.fillStyle=e instanceof mpLinearGradient||e instanceof mpRadialGradient?e.makeGrad(a,c-d,b-d,d*2,d*2):e instanceof mpPattern?e.makePat(a,c-d,b-d):e;__mpCircleHelper(a,c,b,d,f,e)}function __mpCircleHelper(a,c,b,d,f,e){a.beginPath();a.arc(c,b,d,0,Math.PI*2,!0);e&&a.fill();a.stroke()}
function mpEllipse(a,c,b,d,f,e,g){a.beginPath();a.save();a.translate(c,b);a.scale(1,f/d);a.arc(0,0,d,0,Math.PI*2,!0);a.restore();if(e)a.strokeStyle=e instanceof mpLinearGradient||e instanceof mpRadialGradient?e.makeGrad(a,c-d,b-f,d*2,f*2):e instanceof mpPattern?e.makePat(a,c-d,b-f):e;if(g)a.fillStyle=g instanceof mpLinearGradient||g instanceof mpRadialGradient?g.makeGrad(a,c-d,b-f,d*2,f*2):g instanceof mpPattern?g.makePat(a,c-d,b-f):g,a.fill();a.stroke()}
function mpRect(a,c,b,d,f,e,g){if(e)a.strokeStyle=e instanceof mpLinearGradient||e instanceof mpRadialGradient?e.makeGrad(a,c,b,d,f):e instanceof mpPattern?e.makePat(a,c,b):e;if(g)a.fillStyle=g instanceof mpLinearGradient||g instanceof mpRadialGradient?g.makeGrad(a,c,b,d,f):g instanceof mpPattern?g.makePat(a,c,b):g,a.fillRect(c,b,d,f);a.strokeRect(c,b,d,f)}
function mpRoundedRect(a,c,b,d,f,e,g,h){var j=function(a){return a/180*Math.PI};a.beginPath();a.moveTo(c+e,b);a.lineTo(c+d-e,b);a.arc(c+d-e,b+e,e,j(270),j(0),!1);a.lineTo(c+d,b+f-e);a.arc(c+d-e,b+f-e,e,j(0),j(90),!1);a.lineTo(c+e,b+f);a.arc(c+e,b+f-e,e,j(90),j(180),!1);a.lineTo(c,b+e);a.arc(c+e,b+e,e,j(180),j(270),!1);if(g)a.strokeStyle=g instanceof mpLinearGradient||g instanceof mpRadialGradient?g.makeGrad(a,c,b,d,f):g instanceof mpPattern?g.makePat(a,c,b):g;if(h)a.fillStyle=h instanceof mpLinearGradient||
h instanceof mpRadialGradient?h.makeGrad(a,c,b,d,f):h instanceof mpPattern?h.makePat(a,c,b):h,a.fill();a.stroke()}function mpLine(a,c,b,d,f,e){if(e)a.strokeStyle=e instanceof mpLinearGradient||e instanceof mpRadialGradient?e.makeGrad(a,c,b,d-c,f-b):e instanceof mpPattern?e.makePat(a,x,y):e;__mpLineHelper(a,c,b,d,f,e)}function __mpLineHelper(a,c,b,d,f){a.beginPath();a.moveTo(c,b);a.lineTo(d,f);a.stroke()}
function mpText(a,c,b,d,f,e,g){var h=a.measureText(c);g?h.width=g:g=h.width;h.height=a.measureText("m").width;if(f)a.strokeStyle=f instanceof mpLinearGradient||f instanceof mpRadialGradient?f.makeGrad(a,b,d,h.width,h.height):f instanceof mpPattern?f.makePat(a,b,d):f;a.fillStyle=e?e instanceof mpLinearGradient||e instanceof mpRadialGradient?e.makeGrad(a,b,d,h.width,h.height):e instanceof mpPattern?e.makePat(a,b,d):e:a.strokeStyle;a.fillText(c,b,d+h.height,g);a.strokeText(c,b,d+h.height,g)}
function mpImage(a,c,b,d,f,e){e?mpTransTol>0?(c=__mpApplyTransparentColor(a,c,f,e,0,0,c.width,c.height),a.drawImage(c,b,d)):a.drawImage(c,b,d,f,e):(mpTransTol>0&&(c=__mpApplyTransparentColor(a,c,f,e,0,0,c.width,c.height)),a.drawImage(c,b,d))}function mpImageBlitter(a,c,b,d,f,e,g,h,j,k){mpTransTol>0?(c=__mpApplyTransparentColor(a,c,f,e,g,h,j,k),a.drawImage(c,b,d)):a.drawImage(c,g,h,j,k,b,d,f,e)}function mpSetTransColor(a,c,b,d){mpTransR=a;mpTransG=c;mpTransB=b;mpTransTol=d}
function __mpApplyTransparentColor(a,c,b,d,f,e,g,h){a=document.createElement("canvas");a.width=b;a.height=d;var j=a.getContext("2d");j.mozImageSmoothingEnabled=!1;j.drawImage(c,f,e,g,h,0,0,b,d);c=j.getImageData(0,0,b,d);b=c.data;for(d=d=0;d<b.length;d+=4)Math.abs(b[d]-mpTransR)<=mpTransTol&&Math.abs(b[d+1]-mpTransG)<=mpTransTol&&Math.abs(b[d+2]-mpTransB)<=mpTransTol&&(b[d+3]=0);j.putImageData(c,0,0);return a}
function mpLinearGradient(a,c,b,d){this.x1=a;this.y1=c;this.x2=b;this.y2=d;this.stopPos=[];this.stopColor=[];this.numStops=0;this.addColorStop=function(a,b){var c=this.numStops;this.stopPos[c]=a;this.stopColor[c]=b;this.numStops++};this.makeGrad=function(a,b,c,d,j){a=a.createLinearGradient(b+d*this.x1,c+j*this.y1,b+d*this.x2,c+j*this.y2);for(b=0;b<this.numStops;b++)a.addColorStop(this.stopPos[b],this.stopColor[b]);return a}}
function mpRadialGradient(a,c,b,d,f,e){this.x1=a;this.y1=c;this.r1=b;this.x2=d;this.y2=f;this.r2=e;this.stopPos=[];this.stopColor=[];this.numStops=0;this.addColorStop=function(a,b){var c=this.numStops;this.stopPos[c]=a;this.stopColor[c]=b;this.numStops++};this.makeGrad=function(a,b,c,d,e){a=a.createRadialGradient(b+d*this.x1,c+e*this.y1,Math.max(d,e)*this.r1,b+d*this.x2,c+e*this.y2,Math.max(d,e)*this.r2);for(b=0;b<this.numStops;b++)a.addColorStop(this.stopPos[b],this.stopColor[b]);return a}}
function mpPattern(a,c,b,d,f,e){this.img=a;this.type=c;this.xOff=b;this.yOff=d;this.w=f;this.h=e;this.makePat=function(a,b,c){a=Math.floor(b%this.w-this.w);c=Math.floor(c%this.h-this.w);b=document.createElement("canvas");b.width=this.w;b.height=this.h;b.getContext("2d").drawImage(this.img,this.xOff,this.yOff,this.w,this.h);var d=document.createElement("canvas");d.width=this.w;d.height=this.h;var e=d.getContext("2d"),f,l;for(f=0;f<2;f++)for(l=0;l<2;l++)e.drawImage(b,0,0,this.w,this.h,a+this.w*f,c+
this.h*l,this.w,this.h);return e.createPattern(d,this.type)}};
